[tool.poetry]
name = "daffy"
version = "0.1.0"
description = "Pandas Dataframe function decorator"
authors = ["Janne Sinivirta <janne.sinivirta@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7.1"
pandas = "^1.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
isort = "^5.7.0"
black = "^20.8b1"
flake8 = "^3.8.4"
pre-commit = "^2.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3
